# Generated by Django 2.0.13 on 2019-10-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_cd', models.IntegerField(default=0)),
                ('law_cat_cd', models.IntegerField(default=0)),
                ('s_sex', models.IntegerField(default=0)),
                ('s_age', models.IntegerField(default=0)),
                ('s_race', models.IntegerField(default=0)),
                ('v_sex', models.IntegerField(default=0)),
                ('v_age', models.IntegerField(default=0)),
                ('v_race', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Image')),
            ],
        ),
    ]
